spring:
  kafka:
    producer:
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        retries: 2147483647

duffel:
  webhook-secret: ${DUFFEL_WEBHOOK_SECRET}