package com.travel.duffel.internal.config.elasticsearch

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(AirportElasticSearchProperties::class)
class AirportElasticSearchConfig